export const tempData = {
  class: ["bA5Fnc", "CL adJ", "CP Fnc", "CP H,", "CP Lo", "dout", "S ,F", "ALt", "Un,t", ',d', "AP Fnc", "LocFnc", "CS ,n 1", "CS ,n 2"],
  items: [
    ["Cond", "St-b", "HoLd", "trc", "SPd", "Pnt", "P-on", "PoFF", "rnC", "bEEP"],
    [],
    ["CP", "bEP_", "bEP-", "bEP`"],
    [],
    [],
    ["Prt", "AP-P", "AP-b", ",nt", "S-,d", "S-td", "PUSE", "At-F", ",nFo", "Ar-d"],
    ["bPS", "btPr", "CrLF", "tYPE", "t-UP", "ErCd"],
    [],
    [],
    [],
    ["APF", "StAF"],
    ["PASS", "Loc no"],
    [],
    []
  ],
  parameters: [
    [2, 2, 1, 3, 2, 1, 1, 1 ,1 ,1],
    [],
    [4, 1, 1, 1],
    [],
    [],
    [6, 2, 2, 8, 1, 3, 1, 1, 3, 1],
    [5, 2, 1, 5, 1, 1],
    [],
    [],
    [],
    [2, 3],
    [2, 0],
    [],
    []
  ],
  circleIndicator: [
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [],
    [0, 0, 0, 0],
    [],
    [],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [2, 0, 0, 0, 1, 0],
    [],
    [],
    [],
    [0, 0],
    [0, null]
  ],
};
